[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PyIPSA"
authors = [{name = "IPSA", email = "alexander.angelov@tneigroup.com"}]
dynamic = ["version", "description"]
