[build-system]
requires = ["flit_core >=3.2,<4", "hatchling", "pdm-pep517", "poetry-core"]
build-backend = "flit_core.buildapi"

[project]
name = "PyIPSA-rtd"
authors = [{name = "IPSA", email = "support@ipsa-power.com"}]
dynamic = ["version", "description"]
